using System.Diagnostics;
using System.Globalization;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace CLesson.Compiler
{
    /// <summary>
    /// Bir projenin dosyalarını derler. Aynı nesne tekrar kullanıldığında değişmeyen dosyaların
    /// sözdizimi ağaçları yeniden kullanılır (tarayıcıda derlemeyi hızlandırır).
    /// </summary>
    public sealed class ProjectCompiler
    {
        public const string HiddenFileName = "__GizliAyarlar.g.cs";

        static readonly CultureInfo Turkish = new("tr-TR");

        static readonly CSharpParseOptions parseOptions = new(LanguageVersion.Latest, DocumentationMode.None);

        static readonly CSharpCompilationOptions compilationOptions = new(
            OutputKind.WindowsApplication,
            optimizationLevel: OptimizationLevel.Debug,
            allowUnsafe: false,
            concurrentBuild: false,
            nullableContextOptions: NullableContextOptions.Disable,
            checkOverflow: false,
            specificDiagnosticOptions: new Dictionary<string, ReportDiagnostic>
            {
                ["CS8933"] = ReportDiagnostic.Suppress, // global using tekrarı
                ["CS0105"] = ReportDiagnostic.Suppress, // using tekrarı
                ["CS8019"] = ReportDiagnostic.Suppress,
                ["CS1701"] = ReportDiagnostic.Suppress,
                ["CS1702"] = ReportDiagnostic.Suppress,
            });

        readonly Dictionary<string, (string content, SyntaxTree tree)> trees = new();
        CSharpCompilation compilation;
        string currentNamespace;
        List<string> fileOrder = new();

        // Not: System.Threading bilerek yok — "Timer" adı System.Windows.Forms.Timer ile çakışmasın
        // (.NET Framework şablonlarındaki davranış). ZIP'teki csproj de aynı listeyi kullanır.
        public static string HiddenSource(string ns) =>
            "// <auto-generated/>\n" +
            "global using global::System;\n" +
            "global using global::System.Collections.Generic;\n" +
            "global using global::System.Drawing;\n" +
            "global using global::System.IO;\n" +
            "global using global::System.Linq;\n" +
            "global using global::System.Threading.Tasks;\n" +
            "global using global::System.Windows.Forms;\n";

        /// <summary>Projenin dosyalarıyla derleme nesnesini günceller.</summary>
        public CSharpCompilation Update(ProjectInput project)
        {
            var files = project.SourceFiles.ToList();
            var names = new HashSet<string>(files.Select(f => f.Name));
            foreach (var stale in trees.Keys.Where(k => k != HiddenFileName && !names.Contains(k)).ToList()) trees.Remove(stale);

            if (currentNamespace != project.Namespace || !trees.ContainsKey(HiddenFileName))
            {
                currentNamespace = project.Namespace;
                string hidden = HiddenSource(project.Namespace);
                trees[HiddenFileName] = (hidden, Parse(hidden, HiddenFileName));
            }

            foreach (var f in files)
            {
                if (trees.TryGetValue(f.Name, out var existing) && existing.content == f.Content) continue;
                trees[f.Name] = (f.Content, Parse(f.Content, f.Name));
            }

            fileOrder = files.Select(f => f.Name).ToList();
            var ordered = fileOrder.Select(n => trees[n].tree).Append(trees[HiddenFileName].tree).ToList();

            if (compilation == null)
            {
                compilation = CSharpCompilation.Create("OgrenciProjesi", ordered, References.All, compilationOptions);
            }
            else
            {
                compilation = compilation.RemoveAllSyntaxTrees().AddSyntaxTrees(ordered);
            }
            return compilation;
        }

        public IReadOnlyList<string> FileOrder => fileOrder;

        public SyntaxTree TreeOf(string fileName) => trees.TryGetValue(fileName, out var t) ? t.tree : null;

        static SyntaxTree Parse(string content, string path) =>
            CSharpSyntaxTree.ParseText(SourceText.From(content ?? "", Encoding.UTF8), parseOptions, path);

        /// <summary>Yalnızca hataları bulur (kod yazarken anlık denetim için).</summary>
        public List<DiagnosticInfo> Check(ProjectInput project)
        {
            var comp = Update(project);
            var list = new List<Diagnostic>(comp.GetDiagnostics());
            if (!list.Any(d => d.Severity == DiagnosticSeverity.Error))
                list.AddRange(ExtraChecks(comp).diagnostics);
            return Convert(list);
        }

        (List<Diagnostic> diagnostics, Dictionary<SyntaxTree, (Dictionary<TextSpan, string>, HashSet<TextSpan>)> dialogs) ExtraChecks(CSharpCompilation comp)
        {
            var diags = new List<Diagnostic>();
            var dialogs = new Dictionary<SyntaxTree, (Dictionary<TextSpan, string>, HashSet<TextSpan>)>();
            foreach (var tree in comp.SyntaxTrees)
            {
                if (tree.FilePath == HiddenFileName) continue;
                var model = comp.GetSemanticModel(tree);
                var root = tree.GetRoot();
                diags.AddRange(ApiGuard.Check(model, root));
                var (calls, fns, warnings) = Instrumenter.FindAwaitables(model, root);
                diags.AddRange(warnings);
                dialogs[tree] = (calls, fns);
            }
            return (diags, dialogs);
        }

        /// <summary>Projeyi derler ve çalıştırılabilir derlemeyi üretir.</summary>
        public BuildResult Build(ProjectInput project)
        {
            var sw = Stopwatch.StartNew();
            var result = new BuildResult();
            var comp = Update(project);
            result.FileNames = fileOrder.ToList();

            var diagnostics = new List<Diagnostic>(comp.GetDiagnostics());
            if (diagnostics.Any(d => d.Severity == DiagnosticSeverity.Error))
            {
                result.Diagnostics = Convert(diagnostics);
                result.ElapsedMs = sw.ElapsedMilliseconds;
                return result;
            }

            var (extra, dialogs) = ExtraChecks(comp);
            diagnostics.AddRange(extra);
            result.Diagnostics = Convert(diagnostics);
            if (extra.Any(d => d.Severity == DiagnosticSeverity.Error))
            {
                result.ElapsedMs = sw.ElapsedMilliseconds;
                return result;
            }

            // Önce tüm dönüşümlerle, olmazsa daha azıyla dene.
            foreach (var (guards, dialogsOn) in new[] { (true, true), (true, false), (false, false) })
            {
                var instrumented = comp;
                foreach (var tree in comp.SyntaxTrees)
                {
                    if (tree.FilePath == HiddenFileName) continue;
                    int index = fileOrder.IndexOf(tree.FilePath);
                    Dictionary<TextSpan, string> calls = null; HashSet<TextSpan> fns = null;
                    if (dialogsOn && dialogs.TryGetValue(tree, out var d)) (calls, fns) = d;
                    var rewritten = Instrumenter.Rewrite(tree, index, guards, calls, fns);
                    instrumented = instrumented.ReplaceSyntaxTree(tree, rewritten);
                }

                // PDB üretilmez: Roslyn PDB için arka plan görevi bekler, tarayıcıda (tek iş parçacığı) bu mümkün değil.
                // Hata satırları zaten Guard.S ile takip ediliyor.
                using var pe = new MemoryStream();
                var emit = instrumented.Emit(pe);
                if (emit.Success)
                {
                    result.Success = true;
                    result.Assembly = pe.ToArray();
                    break;
                }
                if (!guards)
                {
                    // Bu noktaya gelinmemeli; yine de hatayı kullanıcıya göster.
                    result.Diagnostics.AddRange(Convert(emit.Diagnostics.Where(x => x.Severity == DiagnosticSeverity.Error)));
                }
            }

            result.ElapsedMs = sw.ElapsedMilliseconds;
            return result;
        }

        static List<DiagnosticInfo> Convert(IEnumerable<Diagnostic> diagnostics)
        {
            var list = new List<DiagnosticInfo>();
            foreach (var d in diagnostics)
            {
                if (d.Severity is not (DiagnosticSeverity.Error or DiagnosticSeverity.Warning)) continue;
                if (d.Location.SourceTree?.FilePath == HiddenFileName) continue;
                var span = d.Location.IsInSource ? d.Location.GetLineSpan() : default;
                list.Add(new DiagnosticInfo
                {
                    Severity = d.Severity == DiagnosticSeverity.Error ? "error" : "warning",
                    Code = d.Id,
                    Message = d.GetMessage(Turkish),
                    File = d.Location.IsInSource ? d.Location.SourceTree.FilePath : "",
                    Line = d.Location.IsInSource ? span.StartLinePosition.Line + 1 : 0,
                    Column = d.Location.IsInSource ? span.StartLinePosition.Character + 1 : 0,
                    EndLine = d.Location.IsInSource ? span.EndLinePosition.Line + 1 : 0,
                    EndColumn = d.Location.IsInSource ? span.EndLinePosition.Character + 1 : 0,
                });
            }
            // Aynı hatayı birden çok kez göstermeyelim; önce hatalar, sonra uyarılar.
            return list
                .GroupBy(x => (x.File, x.Line, x.Column, x.Code)).Select(g => g.First())
                .OrderBy(x => x.Severity == "error" ? 0 : 1).ThenBy(x => x.File).ThenBy(x => x.Line)
                .Take(200).ToList();
        }
    }
}
